spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: com.wiki-kafka-consumer-db
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url:  jdbc:mysql://localhost:3306/wikimedia
    username: root
    password: A@bhijeet22b
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect
        "[show_sql]": true
        "[use_sql_comments]": true
        "[format_sql]": true
    hibernate:
      ddl-auto: update         
        

kafka:
  consumer:
    topic: wikimedia_recentchange