spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092 
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  producer:
    topic: wikimedia_recentchange
    
    
wikimedia:
  url: https://stream.wikimedia.org/v2/stream/recentchange